app:
  version: 0.0.1-SNAPSHOT
  api:
    version: 'v1'
  tekton: 'v2'

info:
  application:
    name: 'ReportMicroservice'
    description: 'Report Microservice (ARB report service)'
    version: '0.0.1-SNAPSHOT'

management:
  info:
    env:
      enabled: true
  endpoints:
    prometheus:
      enable: true
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true


  metrics:
    enable:
      all: true
  prometheus:
    metrics:
      export:
        enabled: true
#spring:
#  web:
#    resources:
#      add-mappings: false


server:
  servlet:
    context-path: /api/v1
  port: 8090
  address: 0.0.0.0

spring:
  config:
    import: "classpath:/shared-config.yml"
  profiles:
    active: ${PROFILE_ACTIVE}
  application:
    name: AlRjhi report service

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.springframework: WARN  # Less detailed logging for Spring

